### ISSUE TITLE
Method of producing JDBCTemplate.

### ISSUE THREAD

**Issue by valesOd** [NC-0/OrganizerProject#2]
Может стоить немного изменить код и использовать "JdbcTemplate best practices", а именно в  XML  убрать 
 <bean id="jdbct" class="org.springframework.jdbc.core.JdbcTemplate">
            <property name="dataSource" ref="ds"></property>
</bean>)  
и в DOA заносить "dataSource" 
    public void setDataSource(DataSource dataSource)  {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }
Ну и для примера я сделаю залью сейчас для категории данные конфигурации.
Вот ссылка на спецификацию. http://docs.spring.io/spring/docs/current/spring-framework-reference/html/jdbc.html

**Comment by gadzzzz** [comment]
Если хочешь каждый раз новый jdbcTemplate можно поставить в scope prototype этого бина, хотя не вижу смысла т.к. jdbcTemplate потокобезопасен

**Comment by valesOd** [comment]
Да там пишется что jdbcTemplate потокобезопасен. Но все равно они пишут что общей практикой является... Я лучше приведу конкретный текст из спецификации. 

Instances of the JdbcTemplate class are threadsafe once configured. This is important because it means that you can configure a single instance of a JdbcTemplate and then safely inject this shared reference into multiple DAOs (or repositories). The JdbcTemplate is stateful, in that it maintains a reference to a DataSource, but this state is not conversational state.

A common practice when using the JdbcTemplate class (and the associated NamedParameterJdbcTemplate classes) is to configure a DataSource in your Spring configuration file, and then dependency-inject that shared DataSource bean into your DAO classes; the JdbcTemplate is created in the setter for the DataSource. This leads to DAOs that look in part like the following:

**Comment by gadzzzz** [comment]
Общей практикой, но какие преимущества? А вот все ненужные манипуляции, оставить в бинах, это преимущество)

**Comment by valesOd** [comment]
Окей, насколько я уже понял, они использую данный способ когда идет доступ к нескольким базам. Вопрос снят.
