### ISSUE TITLE
Id in entity(model).

### ISSUE THREAD

**Issue by valesOd** [NC-0/OrganizerProject#3]
Напишите пожалуйста ваше мнение по поводу наличия в сущности(model) поля ид. Мое мнение что данное полу чучуть облегчит работу,а именно сократит один запрос при помощью которого мы бы получали ид, для дальнейшего его использования(например что либо удалить,изменить). Возможно я ошибаюсь. 
Общаясь с несколькими коллегами мнение разделилось, и я предлога принят всем участие.

**Comment by gadzzzz** [comment]
Считаю нужно, т.к. мы не сможем например удалить subtask, не зная его ид

**Comment by valesOd** [comment]
Вот пример на основе нашего проекта.
1) Без ID и передача Email как параметр.

``` java
private void deleteUser(String email){
        Integer id = jdbcTemplate.queryForObject(SqlContent.GET_OBJECT_ID_BY_EMAIL ,new Object[]{email},Integer.class);
        taskDao.deleteByUserId(id);
        categoryDao.deleteByUserId(id);
        jdbcTemplate.update(SqlContent.DELETE_USER_ATTRIBUTES,id);
        jdbcTemplate.update(SqlContent.DELETE_USER_OBJECT,id);
    }
```

2) С ID и передача User как параметр .

``` java
private void deleteUser(User user){
        taskDao.delete(user);
        categoryDao.delete(user);
        jdbcTemplate.update(SqlContent.DELETE_USER_ATTRIBUTES,user.getId());
        jdbcTemplate.update(SqlContent.DELETE_USER_OBJECT,user.getId());
    }
```

**Comment by oleksandr-abasov** [comment]
Уже подымал вопрос, так что естественно за

**Comment by gadzzzz** [comment]
вот тут малеха непонятно, как так вышло что в userDao попали 
taskDao.deleteByUserId(id); и categoryDao.deleteByUserId(id);

**Comment by valesOd** [comment]
Ну, тут скорее всего нужно обратится к моему второму вопросу по поводу делегирования ( https://github.com/NC-0/OrganizerProject/issues/4 ) И для примера я предположил что есть такие методы. Но я бы хотел их также видеть и в реальность, конечно после того как мы обсудим. Мне кажется что будет правильнее ввести такие методы, чем я буду у себя в методе использовать запросы которые также используются в TaskDaoImpl. И я еще хотел обратить внимание на параметры которые передаются, я имею введу что все таки лучше, только email или целый User.

**Comment by valesOd** [comment]
Мнение весь кто хотел высказаться сошлось, и тех кто мне говорил что не стоит этого делать тоже уже поменялось(ну точнее мы не до поняли друг друга в начале). Так как не кто не хочет больше высказать, то вердикт пока таков - Добавляем в сущности id.
