### ISSUE TITLE
Delegating responsibility

### ISSUE THREAD

**Issue by valesOd** [NC-0/OrganizerProject#4]
При решение задачи возможно есть вариант когда лучше реализовать метод в другом классе, к примеру. Необходимо удалить пользователя. Перед тем как удалить пользователя необходимо также удалить все что с ним связано.Что бы не дублировать код, я предлагаю сделать следующее. В классе TaskDaoImpl создать метод delete (User user) - который должен будет удалить все таски связаны с этим пользователем. В свою очередь перед удаление таска необходимо удалить все сабтаски и таск вызовит delete(task) у класса SubTaskImpl. 
И для информирования других разработчик что необходимо создать такой метод, предлагаю trello добавлять в чек лист. Если появляться сомнения то выносить на общее рассмотрение.

**Comment by oleksandr-abasov** [comment]
> > такс вызовит delete(task) у класса SubTaskImpl

И как же произойдет вызов не статичного метода SubTaskImpl из TaskDaoImpl ?

**Comment by forsak3n** [comment]
А откуда и зачем у вас статические методы вообще?

Сергей правильные вещи пишет так-то

**Comment by oleksandr-abasov** [comment]
> > не статичного метода

У нас их нет, как раз об этом я и написал. Перефразирую: где именно произойдет вызов, ведь необходимо иметь ссылку на экземпляр SubTaskImpl. 
А я в Сергее и не сомневался.

**Comment by valesOd** [comment]
Ну насколько я понимаю, у нас это бины, и мы можем их инжекнуть в нужный класс.

**Comment by forsak3n** [comment]
this ^

**Comment by oleksandr-abasov** [comment]
После экспериментов и внимательного прочтения sql кода на создания таблиц, пришли к выводу, что все необходимое было уже сделано с помощью Constraint. 
CONSTRAINT CON_REFERENCE FOREIGN KEY (REFERENCE) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_ROBJECT_ID FOREIGN KEY (OBJECT_ID) REFERENCES OBJECTS (OBJECT_ID) ON DELETE CASCADE,
    CONSTRAINT CON_RATTR_ID FOREIGN KEY (ATTR_ID) REFERENCES ATTRTYPE (ATTR_ID) ON DELETE CASCADE
Итд в других таблицах.
Итог, удаляя в любом Dao, удалиться каскадом и остальная часть. Т.е не будем создавать лишнего.

**Comment by gadzzzz** [comment]
delete objects where object_id in (select reference from objreference where object_id=65);
delete objects where object_id=65;
